"""empty message

Revision ID: 1066923d2dc4
Revises: 4d28fc1fa1f9
Create Date: 2015-04-19 16:02:28.028255

"""

# revision identifiers, used by Alembic.
revision = '1066923d2dc4'
down_revision = '4d28fc1fa1f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_google_id', table_name='users')
    op.drop_column('users', 'google_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    ### end Alembic commands ###
