"""empty message

Revision ID: 2316392fe0ba
Revises: 3329b7f6eeed
Create Date: 2015-03-08 11:44:19.902341

"""

# revision identifiers, used by Alembic.
revision = '2316392fe0ba'
down_revision = '3329b7f6eeed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
