"""empty message

Revision ID: 279cf868db4b
Revises: 2316392fe0ba
Create Date: 2015-03-08 15:15:22.761885

"""

# revision identifiers, used by Alembic.
revision = '279cf868db4b'
down_revision = '2316392fe0ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('species_common', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_name'), 'animals', ['name'], unique=False)
    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('animal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weights')
    op.drop_index(op.f('ix_animals_name'), table_name='animals')
    op.drop_table('animals')
    ### end Alembic commands ###
