"""empty message

Revision ID: 2b907bb4ddab
Revises: 279cf868db4b
Create Date: 2015-03-08 17:09:26.433762

"""

# revision identifiers, used by Alembic.
revision = '2b907bb4ddab'
down_revision = '279cf868db4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
