"""empty message

Revision ID: 3bda51894c45
Revises: None
Create Date: 2015-04-27 15:12:08.742495

"""

# revision identifiers, used by Alembic.
revision = '3bda51894c45'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
