"""empty message

Revision ID: 484c195ce243
Revises: 106f583b8af8
Create Date: 2015-03-11 16:04:14.150545

"""

# revision identifiers, used by Alembic.
revision = '484c195ce243'
down_revision = '106f583b8af8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###
