"""empty message

Revision ID: 4d28fc1fa1f9
Revises: 59cf9a8c118a
Create Date: 2015-04-17 16:07:31.665197

"""

# revision identifiers, used by Alembic.
revision = '4d28fc1fa1f9'
down_revision = '59cf9a8c118a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
