"""empty message

Revision ID: 59cf9a8c118a
Revises: 80943687609
Create Date: 2015-03-30 23:38:05.360054

"""

# revision identifiers, used by Alembic.
revision = '59cf9a8c118a'
down_revision = '80943687609'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
