"""empty message

Revision ID: 80943687609
Revises: 484c195ce243
Create Date: 2015-03-30 23:02:09.517210

"""

# revision identifiers, used by Alembic.
revision = '80943687609'
down_revision = '484c195ce243'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.drop_index('ix_users_nickname', table_name='users')
    op.drop_column('users', 'nickname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_users_nickname', 'users', ['nickname'], unique=True)
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'name')
    op.drop_column('users', 'google_id')
    ### end Alembic commands ###
